Resources:

  MySNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: MySNSNotificationTopic

  MySNSSubscription:
    Type: AWS::SNS::Subscription
    DependsOn: MySNSTopic
    Properties:
      Protocol: email
      # Endpoint: !Ref UserEmail
      Endpoint: "kapoor98.ak@gmail.com"
      TopicArn: !Ref MySNSTopic

  EmailSenderFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: emailSenderLambdaFunction
      Handler: lambda_function.lambda_handler
      # LabRole ARN
      Role: arn:aws:iam::851725512559:role/LabRole
      Code:
        S3Bucket: my-lambda-code-bucket-1
        S3Key: lambda_function.py.zip
      Runtime: python3.8
      Timeout: 30
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref MySNSTopic

Outputs:
  SNSTopicARN:
    Description: ARN of the created SNS topic
    Value: !Ref MySNSTopic